// Pre-rendered transparent ingredient sprites (generated by tools/make-assets.mjs → public/assets/falooda)
const BASE = import.meta.env.BASE_URL

export const A = (name) => `${BASE}assets/falooda/${name}.png`

const JELLY = ['ff86ab', 'a5d98f', 'ffd35f', 'ff9a5c']
export const jellyUrl = (hex) => {
  const k = String(hex || '').replace('#', '').toLowerCase()
  return A(`jelly-${JELLY.includes(k) ? k : 'ff86ab'}`)
}

const ALL = [
  'pistachio', 'pistachio-chip', 'petal', 'petal-2', 'basil', 'cherry', 'almond', 'berry', 'chunk-shade',
  'scoop-shade-a', 'scoop-shade-b', 'scoop-shade-c', 'scoop-vanilla',
  ...JELLY.map((k) => `jelly-${k}`),
].map(A)

// decode every sprite before the opening starts (so nothing pops in while it plays); never blocks longer than `max` ms
export function preloadAssets(max = 2500) {
  const load = (src) =>
    new Promise((res) => {
      const i = new Image()
      i.onload = i.onerror = () => res()
      i.src = src
      i.decode ? i.decode().then(res, res) : null
    })
  return Promise.race([Promise.all(ALL.map(load)), new Promise((r) => setTimeout(r, max))])
}
